#!/bin/bash

MC_HOME=/home/minecraft

if [ ! -f $MC_HOME/eula.txt ]; then
  echo "eula=true" > $MC_HOME/eula.txt
fi

if [ ! -f $MC_HOME/minecraft_server.jar ]; then
  wget https://s3.amazonaws.com/Minecraft.Download/versions/1.10.2/minecraft_server.1.10.2.jar -O $MC_HOME/minecraft_server.jar
fi

cd $MC_HOME; java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui
